### ISSUE TITLE
Despite selecting a keyword by pressing the Enter key, the autocomplete feature continues to display suggestions similar to the chosen keyword

### ISSUE THREAD

**Issue by Sarath-Chandran-P** [reqable/re-editor#10]
Thankyou for this editor. However, I am encountering a persistent issue as follows:

Despite selecting a keyword by pressing the Enter key, the autocomplete feature continues to display suggestions similar to the chosen keyword. For instance, consider the keywords “Apple” and “Apples.” When typing “appl,” the autocomplete suggests both options. After selecting “Apple” and pressing Enter, the autocomplete feature persists in showing “Apples” as a suggested keyword.

It would be greatly appreciated if you could provide a solution to this issue.

Thanks in advance

**Comment by MegatronKing** [comment]
Thanks for the feedback, this does seem to be a problem. I need to think about how to handle this situation.
