### ISSUE TITLE
No implement `updateFloatingCursor` for iOS

### ISSUE THREAD

**Issue by MegatronKing** [reqable/re-editor#12]
**Describe the bug**
The cursor does not move when long pressing the space key.

**Device:**
 - OS: iOS

**Comment by MegatronKing** [comment]
> Hey! Are you currently working on this? Cause if not I was thinking of looking into it myself and see what I can do there.

PR is welcome.

**Comment by pawel-t-wolny** [comment]
I have created an initial version and it looks promising.

https://github.com/user-attachments/assets/568dda71-be48-4394-9a0e-d2a480de845c

Going to polish it up and create a PR this week or the next one.
