### ISSUE TITLE
findController.nextMatch() works only, if the editor does not have the focus

### ISSUE THREAD

**Issue by TomKrauss** [reqable/re-editor#17]
**Describe the bug**
findController.nextMatch() works only, if the editor does not have the focus. This makes it impossible to implement the following feature: pressing some kind of shortcut to jump to the next match while editing the text (like Ctrl+K in IntelliJ) won't work.

**To Reproduce**
1. Add a shortcut to the editor which is bound to an Intent triggering a findController.nextMatch().
2. Perform a find operation
3. Set the focus on the editor and press the named shortcut from 1
4. Nothing happens

**Expected behavior**
We should navigate to the next match in that case.

**Analysis**
The reason nothing works is the following code:
```
/// File _code_editable.dart
  void _onCodeFindChanged() {
    final CodeFindValue? value = widget.findController.value;
    if (value == null) {
      widget.focusNode.requestFocus();
      return;
    }
/// -> prevents further processing. Why is this check necessary? Is it to avoid unintended onCodeFindChanged actions? Can we
/// avoid those using a different check?
    if (widget.focusNode.hasFocus) {
      return;
    }

```

**Device:**
 - OS: Windows Desktop

**Comment by MegatronKing** [comment]
When you open the find panel and focus on find keyword input field, the editor will lose the focus. The shortcuts should bind to the focus of keyword input field rather than the editor.

**Comment by TomKrauss** [comment]
Thank you very much for the clarification. I had another use case in mind (the user wants to step on to the next search result, when the find panel is closed). I found a work around in the meanwhile however to implement this functionality.
