### ISSUE TITLE
Spacebar doesn't work when the Editor is part of PageView

### ISSUE THREAD

**Issue by ShankarKakumani** [reqable/re-editor#22]
I think pageView scrollable is taking over the space control for re_editor

platform: web

**Comment by MegatronKing** [comment]
Sound like not an editor issue, can you provide me more details?

**Comment by ShankarKakumani** [comment]
return PageView(
      children: [
        CodeEditor()
      ],
    );
    
    
    as simple as above code, the space bar inputs are not taking in the CodeEditor().
    I am trying on platform web:
    
    note: I can still use TAB to input space in the code.

**Comment by MegatronKing** [comment]
Thanks very much. I have fixed this.
