### ISSUE TITLE
How to disable auto closing brackets and quotes

### ISSUE THREAD

**Issue by bauripalash** [reqable/re-editor#24]
Is there any way to disable auto closing of brackets and quotes? If yes, how do I do that

**Comment by MegatronKing** [comment]
This option should be provided, but now it is not supported.

**Comment by bauripalash** [comment]
@MegatronKing if till then I want to create a hardcoded fork, would modifying this class be enough for now?

https://github.com/reqable/re-editor/blob/0450f5996894c9b7bcccf7b3e09b7f8133d367cd/lib/src/_code_input.dart#L339
