### ISSUE TITLE
支持 移动Y方向的滚动条

### ISSUE THREAD

**Issue by ismanong** [reqable/re-editor#29]
我有一个实时读取日志文件的功能，当我读取新增行后，需用通过以下代码，

以保证滚动条Y为最底部
_controller.moveCursorToPageEnd();

但此时，如果文本X方向很长（会显示滚动条），滚动条X会移动到最右边， 对自动读取日志这个功能，会显得很怪异。
_controller.moveCursorToLineStart();

经过先移动到文档末尾，再移动到行首。能满足效果。

但会出现一些小瑕疵，就是滚动条X会在移动到行首时，立即显示出来又马上消失。且这样感觉会绕弯，浪费不必要的计算。

![image](https://github.com/user-attachments/assets/cc2c0d2f-2f58-41c9-a606-df39cdda4ac3)

**Comment by MegatronKing** [comment]
@ismanong 你可以自己控制横向和纵向ScrollController的。

**Comment by ismanong** [comment]
谢谢
