### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by Frogperson** [reqable/re-editor#3]
This package uses dart:isolate which is not supported on web platforms:
```
Unsupported operation: dart:isolate is not supported on dart4web
```

https://dart.dev/language/concurrency#concurrency-on-the-web suggests using web works instead. Would it be possible to implement this? After a quick search I found two different packages that might help:
https://pub.dev/packages/isolate_manager
https://pub.dev/packages/isolated_worker

**Comment by MegatronKing** [comment]
@Frogperson Thanks for your suggestion, very helpful. In addition to isolate, there are other issues that need to be handle, such as dart:io. I need some time to do some research.

**Comment by Litt1eQ** [comment]
> This package uses dart:isolate which is not supported on web platforms:
> 
> ```
> Unsupported operation: dart:isolate is not supported on dart4web
> ```
> 
> https://dart.dev/language/concurrency#concurrency-on-the-web suggests using web works instead. Would it be possible to implement this? After a quick search I found two different packages that might help: https://pub.dev/packages/isolate_manager https://pub.dev/packages/isolated_worker

I have supported the web with the isolate_manager, which can be referenced. This has only passed unit testing and the specific performance impact has not been tested.
https://github.com/Litt1eQ/re-editor

**Comment by sgehrman** [comment]
Same issue.  Please merge @Litt1eQ fixes.  It seems to work.

**Comment by Litt1eQ** [comment]
> Same issue. Please merge @Litt1eQ fixes. It seems to work.
> 
> @Litt1eQ could you update your fork to the latest? I'm getting an endless loop in some cases and just want to see if it's fixed.

I have already updated to the latest version of re-editor.

**Comment by sgehrman** [comment]
@Litt1eQ create a pull request.  Maybe they'll merge it if you make it simple for them.  Thanks.
