### ISSUE TITLE
鼠标悬停获取行号和偏移

### ISSUE THREAD

**Issue by 1694439208** [reqable/re-editor#30]
大佬，我看你实现说有MouseTrackerAnnotationTextSpan如何实现鼠标悬停获取当前行号和偏移

**Comment by MegatronKing** [comment]
抱歉，没理解你的意思，具体是什么场景？

**Comment by 1694439208** [comment]
就比如我要自定义自动完成和悬浮显示函数信息，现在的自动完成组件并没有支持鼠标悬浮回调，也许是我没找到
