### ISSUE TITLE
编辑器配置

### ISSUE THREAD

**Issue by 1694439208** [reqable/re-editor#32]
大佬你得编辑器怎么配置的，完全没使用插件的格式化还是自定义了配置，我怎么调都达不到你代码的状态

**Comment by MegatronKing** [comment]
我一般是手动格式化。。。

**Comment by 1694439208** [comment]
大佬要不整个官方插件格式化一下~~我改的挺多 .

**Comment by MegatronKing** [comment]
> 大佬要不整个官方插件格式化一下~~我改的挺多 .

尽量不要格式化代码，因为没法review。
