### ISSUE TITLE
美化功能

### ISSUE THREAD

**Issue by songangweb** [reqable/re-editor#39]
我下载了您的 reqable 项目进行的尝试

想问下在项目里的   自动换行  压缩  美化  这三个功能   能告诉下实现方式吗？

**Comment by MegatronKing** [comment]
- 自动换行，编辑器自带属性配置的。
- 压缩和美化，JsonDecoder先转成Map，再用JsonEncoder将Map转成字符串，转成字符串的时候可以配置是压缩还是不压缩（美化）。

BTW，如果Reqable好用，可以付费支持下哈😄。

**Comment by songangweb** [comment]
No problem  ：）

**Comment by songangweb** [comment]
因为这个 flutter 基础薄弱， 
想问下能否给在 demo 实现出来一个    常驻在文本框上面的  固定的搜索栏目，（这种情况下，跟常用一些） 
并且个人也觉得这样 demo 展示的内容会更完善

**Comment by MegatronKing** [comment]
> 想问下能否给在 demo 实现出来一个 常驻在文本框上面的 固定的搜索栏目，（这种情况下，跟常用一些）

UI的东西每个人想法和需求不一样，我们demo只提供功能基本的演示。
