### ISSUE TITLE
文本搜索项   开启大小写筛选

### ISSUE THREAD

**Issue by songangweb** [reqable/re-editor#40]
使用给到的 demo 测试，     在开启区分大小写的情况下，   

搜索  单词 小写 s  会把大小写的s都标注出来，
但是搜索大写 S 时，则只把大写的 S 标了出来

不确定是否为 bug，还是故意这样设计

**Comment by songangweb** [comment]
![Uploading 13701725961940_.pic.jpg…]()

**Comment by songangweb** [comment]
![13701725961940_ pic](https://github.com/user-attachments/assets/95701fdf-bf4d-445c-821a-82597b7c504f)

**Comment by songangweb** [comment]
➜  re-editor git:(main) ✗ git pull    
Already up to date.

已经是最新的代码了

**Comment by MegatronKing** [comment]
> ![13701725961940_ pic](https://private-user-images.githubusercontent.com/44894211/365990812-95701fdf-bf4d-445c-821a-82597b7c504f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjMyMjgsIm5iZiI6MTcyNTk2MjkyOCwicGF0aCI6Ii80NDg5NDIxMS8zNjU5OTA4MTItOTU3MDFmZGYtYmY0ZC00NDVjLTgyMWEtODI1OTdiN2M1MDRmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDEwMDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYjFjYzVhNjA5NTM3ZmNlNWZlZjVmOWIzNDI0NjMzM2FjYjIzNDkzOGUzZDg0MjRmMDA1N2Q5NTI3ZGFiMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6qMnucTUP6fxHPJ2JECGWISgLaT7su0V26TdYIEBQzM)

没问题啊，这个是没开大小写敏感的搜索结果。

**Comment by songangweb** [comment]
是我理解错了
