### ISSUE TITLE
How to turn off keyword prompt and remove case sensitive in autocomplete?

### ISSUE THREAD

**Issue by Srimathi622** [reqable/re-editor#5]
Hi,
Thanks for this editor. I followed your example code for autocompletion. I want to turn off all auto keywords prompts. I need only "directPrompts" words. It should match with directPrompts whatever I type(Upper or lower case word)  How do I achieve this?
Pls help me.

Thanks in advance
Srimathi

**Comment by Srimathi622** [comment]
Thanks for your reply. Getting this error ('Mode' isn't defined for the type 'SQLWorksheetPageState'.
Try correcting the name to the name of an existing method, or defining a method named 'Mode) When I used Mode() The method. Should I import anything? 

How to remove case sensitive?

**Comment by MegatronKing** [comment]
> How to remove case sensitive

I submitted an update, you can use the master branch and override this function: https://github.com/reqable/re-editor/blob/90457414ef8a8d6e726b39dca0e5c80c996874a1/lib/src/code_autocomplete.dart#L24

**Comment by Srimathi622** [comment]
Thanks for your reply. Let me try to use the code.
