### ISSUE TITLE
Navigation using arrow keys does not permit movement beyond the initially visible option

### ISSUE THREAD

**Issue by Sarath-Chandran-P** [reqable/re-editor#7]
Hi,

I would like to express my gratitude for the editor; it has been indispensable to me. However, I am encountering a problem with the autocompletion functionality: Currently, when utilizing the arrow keys to navigate through the list of suggested keywords, the functionality does not permit movement beyond the initially visible options. For instance, if five keywords are displayed in the autocomplete dropdown, it is not possible to navigate to the sixth keyword or beyond. I would appreciate any assistance you could provide to resolve this matter.

**Comment by MegatronKing** [comment]
@Sarath-Chandran-P Please see this commit: https://github.com/reqable/re-editor/commit/f1198f3e93fe41259c20aabe79a6d0dd5b0c89b7

**Comment by Sarath-Chandran-P** [comment]
Thankyou @MegatronKing
