### ISSUE TITLE
[Mobile] Toolbar and Selection Abnormal work

### ISSUE THREAD

**Issue by canxin121** [reqable/re-editor#8]
During my use on iOS, I found that both double clicking and long pressing will trigger the toolbar, which makes it impossible to move both cursors to select content.

Simultaneously long press and hold to select a section of text, and you will find that only the last selected short section of text is copied to the clipboard after copying.

**Comment by Somtobro** [comment]
Yeah, even on Android. And I also noticed setting controller.text =''; apart from the initState like using a button function makes the keyboard not show again.

**Comment by iraycd** [comment]
I can't select the text on the mobile if I implement `toolbarController`. I want the toolbar on long press or on the selection.
Usually I paste to replace the existing stuff. Which is not possible right now.

**Comment by MegatronKing** [comment]
It was fixed on the latest version.
